"""Actor face pool: generate + manage AI-generated actor faces.

Per follow-up 014: maintains `ai_videos/_actors/actor_NNNN/{actor_NNNN.jpg,
actor_NNNN.md}` folders. Each face is generated by calling pollinations.ai's
free `image.pollinations.ai/prompt/{prompt}` endpoint (no API key, no signup,
MIT-licensed). Each face's sidecar `.md` records its six-field attribute
table + the assembled prompt + the seed.

This module is the first place the backend issues outbound HTTP. Hardening:
- Base URL is hardcoded; the user-controlled portion is the URL-encoded prompt
  path segment, assembled server-side from a closed enum schema.
- 30s per-image timeout; per-image response read cap 5 MiB; batch cap 20.
- HTTP redirects are NOT followed (httpx `follow_redirects=False`).
- Writes only land inside `ai_videos/_actors/actor_NNNN/`.
"""
from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable
from urllib.parse import quote

import httpx

from libs.exposed_tree import ExposedTree
from libs.safe_resolve import SafeResolver

ETHNICITY_OPTIONS: frozenset[str] = frozenset(
    {"asian", "east-asian", "south-asian", "caucasian", "african", "latino", "middle-eastern", "mixed"}
)
GENDER_OPTIONS: frozenset[str] = frozenset({"male", "female"})
AGE_RANGE_OPTIONS: frozenset[str] = frozenset({"18-25", "26-35", "36-50", "51-65", "65+"})
LOOK_OPTIONS: frozenset[str] = frozenset(
    {"handsome", "beautiful", "cute", "mature", "rugged", "soft", "aristocratic", "fierce"}
)
STYLE_OPTIONS: frozenset[str] = frozenset(
    {"modern-casual", "period-ancient-china", "period-western", "business", "streetwear", "sci-fi", "fantasy"}
)

ACTORS_DIR_NAME: str = "_actors"
POLLINATIONS_BASE: str = "https://image.pollinations.ai/prompt/"
DEFAULT_TIMEOUT_SECONDS: float = 30.0
MAX_RESPONSE_BYTES: int = 5 * 1024 * 1024
MAX_BATCH_COUNT: int = 20
MIN_BATCH_COUNT: int = 1
IMAGE_WIDTH: int = 512
IMAGE_HEIGHT: int = 512

_ACTOR_DIR_RE = re.compile(r"^actor_(\d{4,})$")
_ACTOR_ID_RE = re.compile(r"^actor_\d{4,}$")

_STYLE_PROMPT_FRAGMENT: dict[str, str] = {
    "modern-casual": "modern casual outfit, contemporary urban setting",
    "period-ancient-china": "ancient chinese cultivator robes, traditional setting",
    "period-western": "victorian-era period costume",
    "business": "tailored business suit, professional setting",
    "streetwear": "streetwear fashion, urban background",
    "sci-fi": "futuristic sci-fi outfit, neutral backdrop",
    "fantasy": "high-fantasy attire, neutral backdrop",
}

_ETHNICITY_PROMPT_FRAGMENT: dict[str, str] = {
    "asian": "asian",
    "east-asian": "east asian",
    "south-asian": "south asian",
    "caucasian": "caucasian",
    "african": "african",
    "latino": "latino",
    "middle-eastern": "middle eastern",
    "mixed": "mixed ethnicity",
}

_AGE_PROMPT_FRAGMENT: dict[str, str] = {
    "18-25": "around 22 years old",
    "26-35": "around 30 years old",
    "36-50": "around 42 years old",
    "51-65": "around 58 years old",
    "65+": "around 70 years old",
}


class InvalidAttribute(Exception):
    """Raised when an enum field doesn't match the closed schema or count is out of range."""


class GenerationDirMissing(Exception):
    """Raised when the _actors directory cannot be created (filesystem error)."""


@dataclass(frozen=True)
class ActorAttrs:
    ethnicity: str
    gender: str
    age_range: str
    look: str
    style: str
    notes: str = ""

    def to_dict(self) -> dict[str, str]:
        return {
            "ethnicity": self.ethnicity,
            "gender": self.gender,
            "age_range": self.age_range,
            "look": self.look,
            "style": self.style,
            "notes": self.notes,
        }


@dataclass(frozen=True)
class ActorInfo:
    id: str
    attrs: ActorAttrs
    image_path: str
    mtime: float

    def to_dict(self) -> dict[str, object]:
        return {
            "id": self.id,
            "image_path": self.image_path,
            "mtime": self.mtime,
            **self.attrs.to_dict(),
        }


@dataclass
class GenerateResult:
    generated: list[dict[str, object]] = field(default_factory=list)
    errors: list[dict[str, str]] = field(default_factory=list)

    def to_payload(self) -> dict[str, object]:
        return {"generated": list(self.generated), "errors": list(self.errors)}


HttpFetcher = Callable[[str, float, int], bytes]


def _default_fetcher(url: str, timeout: float, max_bytes: int) -> bytes:
    with httpx.Client(follow_redirects=False, timeout=timeout) as client:
        with client.stream("GET", url) as resp:
            resp.raise_for_status()
            buf = bytearray()
            for chunk in resp.iter_bytes():
                buf.extend(chunk)
                if len(buf) > max_bytes:
                    raise ValueError(f"response_too_large (>{max_bytes} bytes)")
            return bytes(buf)


class ActorPool:
    def __init__(
        self,
        exposed: ExposedTree,
        resolver: SafeResolver,
        fetcher: HttpFetcher | None = None,
    ) -> None:
        self._exposed = exposed
        self._resolver = resolver
        self._fetcher = fetcher or _default_fetcher

    def actors_dir(self) -> Path:
        return self._exposed.root / "ai_videos" / ACTORS_DIR_NAME

    def generate_batch(self, attrs: ActorAttrs, count: int) -> GenerateResult:
        self._validate_attrs(attrs)
        if not MIN_BATCH_COUNT <= count <= MAX_BATCH_COUNT:
            raise InvalidAttribute(
                f"count must be between {MIN_BATCH_COUNT} and {MAX_BATCH_COUNT}, got {count}"
            )
        actors_dir = self.actors_dir()
        try:
            actors_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            raise GenerationDirMissing(str(exc))

        prompt = self._build_prompt(attrs)
        result = GenerateResult()
        base_seed = int(time.time() * 1000)
        next_id_num = self._next_actor_id_num(actors_dir)
        for i in range(count):
            actor_num = next_id_num + i
            actor_id = f"actor_{actor_num:04d}"
            seed = base_seed + i
            actor_folder = actors_dir / actor_id
            try:
                actor_folder.mkdir(parents=True, exist_ok=False)
            except FileExistsError:
                result.errors.append({"requested_id": actor_id, "message": "folder_already_exists"})
                continue
            except OSError as exc:
                result.errors.append({"requested_id": actor_id, "message": f"mkdir_failed: {exc}"})
                continue
            url = self._build_url(prompt, seed)
            try:
                image_bytes = self._fetcher(url, DEFAULT_TIMEOUT_SECONDS, MAX_RESPONSE_BYTES)
            except Exception as exc:
                result.errors.append({"requested_id": actor_id, "message": f"http_failed: {exc}"})
                self._cleanup_empty_folder(actor_folder)
                continue
            if not image_bytes:
                result.errors.append({"requested_id": actor_id, "message": "empty_response"})
                self._cleanup_empty_folder(actor_folder)
                continue
            jpg_path = actor_folder / f"{actor_id}.jpg"
            md_path = actor_folder / f"{actor_id}.md"
            try:
                jpg_path.write_bytes(image_bytes)
                md_path.write_text(
                    self._build_sidecar(actor_id, attrs, prompt, seed),
                    encoding="utf-8",
                )
            except OSError as exc:
                result.errors.append({"requested_id": actor_id, "message": f"write_failed: {exc}"})
                self._cleanup_empty_folder(actor_folder)
                continue
            rel_image = self._rel(jpg_path)
            result.generated.append(
                {
                    "id": actor_id,
                    "image_path": rel_image,
                    "attrs": attrs.to_dict(),
                    "seed": seed,
                }
            )
        return result

    def list_actors(self) -> list[ActorInfo]:
        actors_dir = self.actors_dir()
        if not actors_dir.is_dir():
            return []
        out: list[ActorInfo] = []
        for child in sorted(actors_dir.iterdir(), key=lambda p: p.name):
            if not child.is_dir() or child.is_symlink():
                continue
            match = _ACTOR_DIR_RE.match(child.name)
            if not match:
                continue
            actor_id = child.name
            jpg_path = child / f"{actor_id}.jpg"
            md_path = child / f"{actor_id}.md"
            if not jpg_path.is_file() or not md_path.is_file():
                continue
            attrs = self._parse_sidecar(md_path)
            if attrs is None:
                continue
            try:
                mtime = jpg_path.stat().st_mtime
            except OSError:
                continue
            out.append(ActorInfo(id=actor_id, attrs=attrs, image_path=self._rel(jpg_path), mtime=mtime))
        return out

    def actor_exists(self, actor_id: str) -> bool:
        if not _ACTOR_ID_RE.match(actor_id):
            return False
        folder = self.actors_dir() / actor_id
        if not folder.is_dir():
            return False
        return (folder / f"{actor_id}.jpg").is_file()

    @staticmethod
    def _validate_attrs(attrs: ActorAttrs) -> None:
        if attrs.ethnicity not in ETHNICITY_OPTIONS:
            raise InvalidAttribute(f"ethnicity={attrs.ethnicity!r} not in schema")
        if attrs.gender not in GENDER_OPTIONS:
            raise InvalidAttribute(f"gender={attrs.gender!r} not in schema")
        if attrs.age_range not in AGE_RANGE_OPTIONS:
            raise InvalidAttribute(f"age_range={attrs.age_range!r} not in schema")
        if attrs.look not in LOOK_OPTIONS:
            raise InvalidAttribute(f"look={attrs.look!r} not in schema")
        if attrs.style not in STYLE_OPTIONS:
            raise InvalidAttribute(f"style={attrs.style!r} not in schema")
        if len(attrs.notes) > 500:
            raise InvalidAttribute("notes must be ≤ 500 characters")

    @staticmethod
    def _build_prompt(attrs: ActorAttrs) -> str:
        ethn = _ETHNICITY_PROMPT_FRAGMENT[attrs.ethnicity]
        age = _AGE_PROMPT_FRAGMENT[attrs.age_range]
        style = _STYLE_PROMPT_FRAGMENT[attrs.style]
        parts = [
            f"portrait headshot of {ethn} {attrs.gender}",
            age,
            attrs.look,
            style,
            "professional studio lighting",
            "neutral background",
            "photorealistic",
            "sharp focus",
            "8k",
        ]
        return ", ".join(parts)

    @staticmethod
    def _build_url(prompt: str, seed: int) -> str:
        encoded = quote(prompt, safe="")
        return (
            f"{POLLINATIONS_BASE}{encoded}"
            f"?model=flux&width={IMAGE_WIDTH}&height={IMAGE_HEIGHT}&seed={seed}&nologo=true"
        )

    @staticmethod
    def _next_actor_id_num(actors_dir: Path) -> int:
        max_num = 0
        try:
            entries = list(actors_dir.iterdir())
        except OSError:
            return 1
        for entry in entries:
            if not entry.is_dir():
                continue
            m = _ACTOR_DIR_RE.match(entry.name)
            if not m:
                continue
            n = int(m.group(1))
            if n > max_num:
                max_num = n
        return max_num + 1

    @staticmethod
    def _build_sidecar(actor_id: str, attrs: ActorAttrs, prompt: str, seed: int) -> str:
        notes_display = attrs.notes if attrs.notes else "—"
        return (
            f"# {actor_id}\n"
            f"\n"
            f"AI-generated actor face (pollinations.ai, follow-up 014).\n"
            f"\n"
            f"| 字段 | 值 |\n"
            f"|---|---|\n"
            f"| ethnicity | {attrs.ethnicity} |\n"
            f"| gender | {attrs.gender} |\n"
            f"| age_range | {attrs.age_range} |\n"
            f"| look | {attrs.look} |\n"
            f"| style | {attrs.style} |\n"
            f"| notes | {notes_display} |\n"
            f"| seed | {seed} |\n"
            f"\n"
            f"## 生成 prompt\n"
            f"\n"
            f"```\n"
            f"{prompt}\n"
            f"```\n"
        )

    @staticmethod
    def _parse_sidecar(md_path: Path) -> ActorAttrs | None:
        try:
            text = md_path.read_text(encoding="utf-8")
        except OSError:
            return None
        fields: dict[str, str] = {}
        for line in text.splitlines():
            line = line.strip()
            if not line.startswith("|"):
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            if len(cells) != 2:
                continue
            key, value = cells[0], cells[1]
            if key in {"ethnicity", "gender", "age_range", "look", "style", "notes"}:
                fields[key] = value if value != "—" else ""
        try:
            return ActorAttrs(
                ethnicity=fields["ethnicity"],
                gender=fields["gender"],
                age_range=fields["age_range"],
                look=fields["look"],
                style=fields["style"],
                notes=fields.get("notes", ""),
            )
        except KeyError:
            return None

    def _rel(self, p: Path) -> str:
        try:
            return p.resolve().relative_to(self._resolver.root).as_posix()
        except (OSError, ValueError):
            return p.as_posix()

    @staticmethod
    def _cleanup_empty_folder(folder: Path) -> None:
        try:
            if folder.is_dir() and not any(folder.iterdir()):
                folder.rmdir()
        except OSError:
            pass


__all__ = [
    "ACTORS_DIR_NAME",
    "ActorAttrs",
    "ActorInfo",
    "ActorPool",
    "AGE_RANGE_OPTIONS",
    "ETHNICITY_OPTIONS",
    "GENDER_OPTIONS",
    "GenerateResult",
    "GenerationDirMissing",
    "HttpFetcher",
    "InvalidAttribute",
    "LOOK_OPTIONS",
    "MAX_BATCH_COUNT",
    "MIN_BATCH_COUNT",
    "POLLINATIONS_BASE",
    "STYLE_OPTIONS",
]
