"""Actor face pool: generate + manage AI-generated actor faces.

Per follow-up 014: maintains `ai_videos/_actors/actor_NNNN/{actor_NNNN.jpg,
actor_NNNN.md}` folders. Each face is generated by an external AI image
provider. Each face's sidecar `.md` records its six-field attribute table +
the assembled prompt + the seed.

Per follow-up 025: provider surface collapsed to Kling-only. The previous
Pollinations + AI Horde + ProviderChain fallback (follow-ups 021 + 024) was
retired because Kling's commercial endpoint (~1-3s/img, JWT auth, stable)
made the chain's failure-mode insurance moot while keeping three outbound
hosts in the SSRF surface. `KLING_ACCESS_KEY` + `KLING_SECRET_KEY` are now
required (loaded by `libs.env_loader` from `backend/.env`); missing keys
raise at construction time (startup failfast).

Hardening for outbound HTTP:
- Base URL is hardcoded; the user-controlled portion is the prompt text,
  assembled server-side from a closed enum schema (FR-86).
- 30s timeout, 5 MiB response cap per fetch.
- JWT secret never logged, never embedded in URLs, never returned.
- Download URL is SSRF-vetted (https + non-loopback / RFC1918 / link-local
  / multicast / reserved) before the bytes are fetched.
- Writes only land inside `ai_videos/_actors/actor_NNNN/`.
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import ipaddress
import json
import os
import random
import re
import socket
import time
from dataclasses import dataclass, field
from io import BytesIO
from pathlib import Path
from urllib.parse import urlparse

import httpx
from PIL import Image

from libs.exposed_tree import ExposedTree
from libs.safe_resolve import SafeResolver

ETHNICITY_OPTIONS: frozenset[str] = frozenset(
    {"asian", "east-asian", "south-asian", "caucasian", "african", "latino", "middle-eastern", "mixed"}
)
GENDER_OPTIONS: frozenset[str] = frozenset({"male", "female"})
AGE_RANGE_OPTIONS: frozenset[str] = frozenset({"18-25", "26-35", "36-50", "51-65", "65+"})
LOOK_OPTIONS: frozenset[str] = frozenset(
    {"handsome", "beautiful", "cute", "mature", "rugged", "soft", "aristocratic", "fierce"}
)
STYLE_OPTIONS: frozenset[str] = frozenset(
    {"modern-casual", "period-ancient-china", "period-western", "business", "streetwear", "sci-fi", "fantasy"}
)

ACTORS_DIR_NAME: str = "_actors"
DEFAULT_TIMEOUT_SECONDS: float = 30.0
MAX_RESPONSE_BYTES: int = 5 * 1024 * 1024
MAX_BATCH_COUNT: int = 50
MIN_BATCH_COUNT: int = 1
IMAGE_WIDTH: int = 512
IMAGE_HEIGHT: int = 512
_MAX_ID_ALLOC_SCAN: int = 1000
JPEG_QUALITY: int = 95

# Per follow-up 029: resolution presets pick a target pixel size for the
# saved JPEG. `None` means use Kling's native output (~1024px for kling-v1
# 1:1) without resampling. Other values trigger a Pillow LANCZOS resize.
_RESOLUTION_PRESETS: dict[str, int | None] = {
    "normal": None,
    "2k": 2048,
    "4k": 4096,
}
DEFAULT_RESOLUTION: str = "normal"
RESOLUTION_OPTIONS: frozenset[str] = frozenset(_RESOLUTION_PRESETS.keys())

_ACTOR_DIR_RE = re.compile(r"^actor_(\d{4,})$")
_ACTOR_ID_RE = re.compile(r"^actor_\d{4,}$")
_NEW_FILENAME_RE = re.compile(r"^[^/\\]+__[^/\\]+__[^/\\]+\.jpg$")


def _attrs_to_filename(attrs: "ActorAttrs") -> str:
    """Per follow-up 033: jpg files named {ethnicity}__{gender}__{age_range}.jpg
    inside the actor's folder. Double-underscore separator avoids collision
    with css-class naming and is distinctive enough to spot at a glance."""
    return f"{attrs.ethnicity}__{attrs.gender}__{attrs.age_range}.jpg"


def _find_actor_jpg(actor_folder: Path) -> Path | None:
    """Return the actor's jpg file path, preferring the follow-up 033
    descriptive naming over the legacy `{actor_id}.jpg` name. Returns None
    if the folder contains no jpg."""
    for child in actor_folder.iterdir() if actor_folder.is_dir() else []:
        if child.is_file() and _NEW_FILENAME_RE.match(child.name):
            return child
    # Fallback: legacy `{actor_id}.jpg` for not-yet-migrated folders.
    legacy = actor_folder / f"{actor_folder.name}.jpg"
    if legacy.is_file():
        return legacy
    return None

_STYLE_PROMPT_FRAGMENT: dict[str, str] = {
    "modern-casual": "modern casual outfit, contemporary urban setting",
    "period-ancient-china": "ancient chinese cultivator robes, traditional setting",
    "period-western": "victorian-era period costume",
    "business": "tailored business suit, professional setting",
    "streetwear": "streetwear fashion, urban background",
    "sci-fi": "futuristic sci-fi outfit, neutral backdrop",
    "fantasy": "high-fantasy attire, neutral backdrop",
}

_ETHNICITY_PROMPT_FRAGMENT: dict[str, str] = {
    "asian": "asian",
    "east-asian": "east asian",
    "south-asian": "south asian",
    "caucasian": "caucasian",
    "african": "african",
    "latino": "latino",
    "middle-eastern": "middle eastern",
    "mixed": "mixed ethnicity",
}

_AGE_PROMPT_FRAGMENT: dict[str, str] = {
    "18-25": "around 22 years old",
    "26-35": "around 30 years old",
    "36-50": "around 42 years old",
    "51-65": "around 58 years old",
    "65+": "around 70 years old",
}

# Per follow-up 027 + 029: variance pools injected per-image so a single
# batch produces visually distinct faces instead of near-duplicates. Each
# image draws multiple fragments from 17 pools (look archetype +
# 6 facial parts + 3 hair sub-axes + 2 skin sub-axes + expression / mood /
# lighting / photography), seeded by the actor's seed for reproducibility.
# Output ≥ 1000 chars per image (follow-up 029 explicit requirement).
# All fragments are English to stay consistent with the base prompt.

_VARIANCE_LOOK_MALE: tuple[str, ...] = (
    "fresh-faced youthful idol type with effortless charm",
    "delicate refined gentleman with soft scholarly poise",
    "clean-cut classic handsome with all-American polish",
    "alluring mysterious bad-boy aura with brooding intensity",
    "rugged seasoned warrior bearing with weathered confidence",
    "scholarly intellectual presence with thoughtful demeanor",
    "boyish playful charm with infectious mischievous energy",
    "stoic noble bearing with disciplined regal composure",
    "charismatic leader presence radiating quiet authority",
    "approachable warm-hearted neighbor with kind sincerity",
    "introspective artistic soul with poetic melancholic vibe",
    "athletic confident vigor with sun-bronzed sporty appeal",
    "sleek modern fashion-forward profile with editorial edge",
    "old-soul classical scholar with timeless dignified gravitas",
)
_VARIANCE_LOOK_FEMALE: tuple[str, ...] = (
    "youthful innocent freshness with luminous girl-next-door appeal",
    "delicate refined elegance with porcelain-doll grace",
    "classic clean beauty with timeless heritage-magazine poise",
    "alluring sultry mystique with smoky femme-fatale intensity",
    "fierce independent spirit with sharp commanding presence",
    "scholarly intellectual grace with quiet introspective depth",
    "playful spirited charm with effortless mischievous energy",
    "noble aristocratic bearing with disciplined ballet-trained poise",
    "charismatic radiant presence with magnetic stage-lit warmth",
    "approachable warm-hearted glow with sunlit cottagecore softness",
    "introspective artistic depth with painterly Pre-Raphaelite mood",
    "athletic confident strength with toned dancer-like vigor",
    "sleek modern editorial profile with high-fashion sharpness",
    "ethereal otherworldly quality with moonlit dreamy serenity",
)
_VARIANCE_FACE_FEATURES_MALE: tuple[str, ...] = (
    "sharply defined masculine bone structure with strong contours",
    "softly youthful features with smooth boyish proportions",
    "rugged weathered features with character-rich lived-in texture",
    "aristocratic refined features with patrician elegance",
    "balanced symmetrical features with classical photogenic harmony",
    "exotic mixed-heritage features with intriguing cross-cultural blend",
    "lean angular features with model-thin facial structure",
    "broad open features with friendly trustworthy expressiveness",
    "delicately androgynous features with refined gender-fluid grace",
    "chiseled action-hero features with cinematic leading-man strength",
    "warm friendly features with approachable everyman quality",
    "stern serious features with disciplined military bearing",
)
_VARIANCE_FACE_FEATURES_FEMALE: tuple[str, ...] = (
    "delicately refined feminine features with porcelain-fine bone structure",
    "softly rounded youthful features with smooth dewy proportions",
    "elegantly mature features with sophisticated lived-in poise",
    "aristocratic patrician features with regal old-money refinement",
    "balanced symmetrical features with classical magazine-cover harmony",
    "exotic mixed-heritage features with captivating cross-cultural blend",
    "lean angular features with high-fashion model proportions",
    "warmly open features with friendly relatable expressiveness",
    "delicately androgynous features with willowy gender-fluid grace",
    "striking dramatic features with theatrical stage-ready presence",
    "soft natural features with unforced no-makeup beauty",
    "sharply defined features with editorial avant-garde intensity",
)
_VARIANCE_JAWLINE: tuple[str, ...] = (
    "strong defined square jawline with masculine angularity",
    "soft rounded jawline with youthful gentle curves",
    "narrow tapered V-shaped jawline with feminine refinement",
    "subtle delicate jawline with soft natural transitions",
    "sharp chiseled jawline with model-grade definition",
    "broad solid jawline with grounded stable strength",
    "elegant heart-shaped jawline with romantic gentle taper",
    "powerful Roman-bust jawline with classical sculpted gravitas",
    "softly oval jawline with balanced photogenic proportions",
    "slightly cleft chin with subtle character dimple",
)
_VARIANCE_CHEEKBONES: tuple[str, ...] = (
    "high prominent cheekbones with elegant sculpted definition",
    "softly rounded cheekbones with youthful apple-cheek fullness",
    "subtly defined cheekbones with natural understated structure",
    "sharply angled cheekbones with high-fashion model definition",
    "warmly full cheekbones with healthy rosy plumpness",
    "hollow defined cheekbones with refined ascetic structure",
    "broad cheekbones with strong heritage facial breadth",
    "delicately tapered cheekbones with porcelain-fine refinement",
    "softly contoured cheekbones with painterly chiaroscuro shading",
)
_VARIANCE_BROW: tuple[str, ...] = (
    "thick masculine eyebrows with bold natural fullness",
    "softly arched feminine eyebrows with delicate refined shaping",
    "straight bold eyebrows with strong horizontal expressiveness",
    "delicately shaped eyebrows with editorial fine grooming",
    "dramatic angled eyebrows with high theatrical lift",
    "natural untamed eyebrows with relaxed effortless texture",
    "lifted alert eyebrows with engaged inquisitive expression",
    "heavy serious eyebrows with thoughtful intense gravitas",
    "tapered fine eyebrows with classical elegant arch",
    "slightly furrowed eyebrows with intense focused concentration",
)
_VARIANCE_NOSE: tuple[str, ...] = (
    "straight aquiline nose with elegant aristocratic bridge",
    "softly rounded nose with youthful gentle proportions",
    "pert button nose with cute upturned tip",
    "strong Roman nose with classical sculpted prominence",
    "refined narrow nose with high-fashion model thinness",
    "slightly upturned nose with playful expressive lift",
    "broad bridged nose with grounded heritage strength",
    "delicately tapered nose with porcelain-fine refinement",
    "asymmetric character nose with intriguing lived-in story",
    "softly defined nose with painterly natural shading",
)
_VARIANCE_LIPS: tuple[str, ...] = (
    "full sensuous lips with rich natural pigmentation",
    "thin elegantly defined lips with refined sculpted contour",
    "cupid-bow-shaped lips with classical heart-pretty arch",
    "softly pursed lips with thoughtful quiet expressiveness",
    "wide expressive lips with cinematic ready-to-speak presence",
    "naturally smiling lips with warm engaging upturn",
    "slightly parted lips with breath-paused candid moment",
    "perfectly balanced lips with editorial-perfect proportions",
    "rich pillowy lips with soft dewy moisture",
    "tightly closed lips with quiet stoic composure",
)
_VARIANCE_EYES: tuple[str, ...] = (
    "large round expressive eyes with luminous open clarity",
    "narrow phoenix-shaped eyes with elegant elongated lift",
    "deep-set thoughtful eyes with brooding contemplative depth",
    "wide innocent eyes with childlike wondering openness",
    "sharply piercing eyes with intense focused gaze",
    "softly dreamy eyes with romantic hazy serenity",
    "monolid stylized eyes with sleek graphic definition",
    "double-eyelid pronounced eyes with crisp defined fold",
    "heavy-lidded sultry eyes with smoky bedroom intensity",
    "sparkling bright eyes with lively engaged vivacity",
    "dark intense eyes with mysterious unreadable depth",
    "clear bright eyes with crystal-pure honest transparency",
    "almond-shaped catlike eyes with feline sharp grace",
    "softly upturned smile-eyes with crinkled joyful warmth",
)
_VARIANCE_HAIR_LENGTH: tuple[str, ...] = (
    "extremely short cropped hair with military precision cut",
    "short tapered hair with modern barbershop fade",
    "medium-length tousled hair with effortless texture",
    "shoulder-length layered hair with soft natural movement",
    "long flowing hair cascading past the collarbone",
    "extra-long hair extending to the mid-back",
    "chin-length bob hair with sharp geometric line",
    "asymmetric undercut with bold contrasting lengths",
)
_VARIANCE_HAIR_STYLE: tuple[str, ...] = (
    "neatly side-parted hair with classic gentleman finish",
    "center-parted hair with symmetrical balanced flow",
    "messy bedhead style with effortless lived-in volume",
    "slicked-back hair with glossy editorial polish",
    "wavy textured hair with soft beachy movement",
    "straight smooth hair with sleek glass-finish polish",
    "curly voluminous hair with bouncy natural spring",
    "braided hair with intricate woven detail",
    "high ponytail with sharp pulled-back tension",
    "loose half-up half-down style with relaxed casual elegance",
)
_VARIANCE_HAIR_COLOR: tuple[str, ...] = (
    "jet-black hair with deep glossy reflectivity",
    "dark brown hair with warm chocolate undertones",
    "warm chestnut hair with rich autumnal highlights",
    "rich auburn hair with copper sunlit warmth",
    "honey blonde hair with golden sunkissed glow",
    "silvery-white hair with cool platinum sheen",
    "ash brown hair with cool muted neutrality",
    "deep raven hair with blue-black highlights",
    "soft caramel hair with creamy balayage gradient",
    "dyed pastel-tinted hair with soft creative wash",
)
_VARIANCE_SKIN_TONE: tuple[str, ...] = (
    "porcelain-fair skin with cool pink undertones",
    "ivory-pale skin with delicate translucent quality",
    "warm beige skin with golden neutral undertones",
    "honey-warm skin with sunlit golden radiance",
    "wheatish complexion with warm tan undertones",
    "olive complexion with cool green-gold balance",
    "bronze sun-kissed skin with warm tropical glow",
    "deep mocha skin with rich warm undertones",
    "softly tanned skin with healthy outdoor radiance",
    "fair freckled skin with charming dappled texture",
)
_VARIANCE_SKIN_TEXTURE: tuple[str, ...] = (
    "dewy radiant skin with luminous freshly-hydrated glow",
    "matte smooth skin with editorial-perfect powder finish",
    "softly luminous skin with painterly natural light absorption",
    "glowing healthy skin with vital well-rested vibrance",
    "clear pristine skin with porcelain unblemished smoothness",
    "subtle natural texture with realistic photographed pores",
    "rosy flushed skin with warm circulating undertones",
    "softly weathered skin with character-rich lived-in patina",
)
_VARIANCE_EXPRESSION: tuple[str, ...] = (
    "gentle quiet smile with kind disarming warmth",
    "neutral confident gaze with steady self-assured calm",
    "smoldering intense look with magnetic locked-in focus",
    "faint enigmatic smirk with hint-of-knowing playfulness",
    "serene calm expression with meditative inner stillness",
    "contemplative thoughtful look with poetic introspection",
    "engaging direct eye-contact with warm trustworthy openness",
    "mysterious distant expression with unreadable poetic remove",
    "warm inviting smile with engaged conversational presence",
    "playful mischievous grin with twinkling shared-secret energy",
    "stoic dignified expression with composed regal restraint",
    "vulnerable open expression with raw emotional honesty",
)
_VARIANCE_MOOD: tuple[str, ...] = (
    "cinematic editorial atmosphere with magazine-grade gravitas",
    "vintage timeless mood with classical 1950s heritage tone",
    "modern contemporary energy with crisp present-day sharpness",
    "classical refined ambiance with old-master oil-painting grace",
    "urban edgy vibe with street-photography immediacy",
    "pastoral natural mood with sunlit countryside warmth",
    "dreamy ethereal atmosphere with diffuse fairytale softness",
    "dramatic theatrical mood with stage-lit operatic intensity",
    "minimalist clean aesthetic with negative-space breathing room",
    "rich painterly mood with Caravaggio chiaroscuro depth",
)
_VARIANCE_LIGHTING: tuple[str, ...] = (
    "soft diffused window light with gentle wraparound gradient",
    "dramatic chiaroscuro lighting with deep contrast shadows",
    "golden-hour warm sunlight with amber sunset glow",
    "studio Rembrandt lighting with classical triangle cheekbone highlight",
    "butterfly beauty lighting with symmetrical under-nose shadow",
    "split lighting with bold half-shadow facial division",
    "rim-lit silhouette with bright contour separation",
    "open-shade natural lighting with even soft daylight",
    "moody low-key lighting with deep velvet shadows",
    "high-key bright lighting with airy minimal-shadow cheerfulness",
)
_VARIANCE_PHOTOGRAPHY: tuple[str, ...] = (
    "shallow depth-of-field with creamy bokeh background",
    "tack-sharp focus with crystal-clear pore-level detail",
    "subtle film-grain texture with analog cinematic warmth",
    "glossy magazine-quality finish with luxurious print sheen",
    "candid documentary feel with unposed authentic moment",
    "posed editorial style with deliberate art-directed composition",
    "hyper-detailed photorealism with skin-pore micro-texture",
    "softly bokehed background with dreamy out-of-focus blur",
    "85mm portrait lens compression with flattering facial proportions",
    "medium-format large-sensor look with rich tonal gradation",
)

# Per follow-up 031: photorealism / anti-wax pool. Real camera + film stock
# cues that consistently push Kling toward "real photograph" rather than
# "CG / waxwork / smooth AI face". Each batch's seed picks a different
# camera/film combo so a row of generated actors reads as photographed by
# multiple photographers rather than one AI model.
_VARIANCE_PHOTOREALISM: tuple[str, ...] = (
    "shot on Canon EOS R5 with 85mm f/1.4 prime lens, true skin micro-texture",
    "shot on Sony A7 IV with 50mm f/1.8, natural color science, candid framing",
    "shot on Fujifilm X-T5 with classic-chrome film simulation, organic grain",
    "Hasselblad medium-format portrait, painterly tonal gradation, real skin pores",
    "Kodak Portra 400 35mm film grain, warm naturalistic skin tones, slight halation",
    "Cinestill 800T film stock, gentle halation around highlights, cinematic realism",
    "Leica M11 rangefinder candid, natural ambient light, lived-in skin texture",
    "iPhone 15 Pro candid photo, slightly imperfect framing, true-to-life skin",
    "Nikon Z9 with 105mm f/1.4, ultra-natural rendering, no skin smoothing",
    "Pentax 67 medium-format portrait, deep tonal range, visible facial micro-detail",
    "old-school 35mm point-and-shoot snapshot, slight motion sway, real-life feel",
    "Polaroid SX-70 instant photograph, soft chemical color shift, candid honesty",
)


def _variance_for(seed: int, gender: str) -> str:
    """Build a per-image variance phrase ≥ 1000 chars (follow-up 029).

    Draws multiple fragments from 17 pools (look archetype + 6 facial parts +
    3 hair sub-axes + 2 skin sub-axes + expression / mood / lighting /
    photography) using a seeded RNG so the same seed reproduces the same
    variance. Picks per-pool counts are tuned to land in the 1000-1500 char
    range; the length guard at the bottom appends more photography
    descriptors if the assembled string falls short.
    """
    rng = random.Random(seed)
    look_pool = _VARIANCE_LOOK_FEMALE if gender == "female" else _VARIANCE_LOOK_MALE
    features_pool = (
        _VARIANCE_FACE_FEATURES_FEMALE if gender == "female" else _VARIANCE_FACE_FEATURES_MALE
    )
    parts: list[str] = []
    parts.append(rng.choice(look_pool))
    parts.extend(rng.sample(features_pool, k=min(2, len(features_pool))))
    parts.append(rng.choice(_VARIANCE_JAWLINE))
    parts.append(rng.choice(_VARIANCE_CHEEKBONES))
    parts.append(rng.choice(_VARIANCE_BROW))
    parts.append(rng.choice(_VARIANCE_NOSE))
    parts.append(rng.choice(_VARIANCE_LIPS))
    parts.extend(rng.sample(_VARIANCE_EYES, k=min(2, len(_VARIANCE_EYES))))
    parts.append(rng.choice(_VARIANCE_HAIR_LENGTH))
    parts.append(rng.choice(_VARIANCE_HAIR_STYLE))
    parts.append(rng.choice(_VARIANCE_HAIR_COLOR))
    parts.append(rng.choice(_VARIANCE_SKIN_TONE))
    parts.append(rng.choice(_VARIANCE_SKIN_TEXTURE))
    parts.extend(rng.sample(_VARIANCE_EXPRESSION, k=min(2, len(_VARIANCE_EXPRESSION))))
    parts.append(rng.choice(_VARIANCE_MOOD))
    parts.extend(rng.sample(_VARIANCE_LIGHTING, k=min(2, len(_VARIANCE_LIGHTING))))
    parts.extend(rng.sample(_VARIANCE_PHOTOGRAPHY, k=min(3, len(_VARIANCE_PHOTOGRAPHY))))
    parts.extend(rng.sample(_VARIANCE_PHOTOREALISM, k=min(2, len(_VARIANCE_PHOTOREALISM))))
    result = ", ".join(parts)
    # 1000-char floor: append more photography descriptors if the pool draws
    # happened to land short. In practice the default schedule yields ~1100
    # chars; this is a safety net, not the normal path.
    while len(result) < 1000:
        extra = rng.choice(_VARIANCE_PHOTOGRAPHY)
        result = result + ", " + extra
    return result


class InvalidAttribute(Exception):
    """Raised when an enum field doesn't match the closed schema or count is out of range."""


class GenerationDirMissing(Exception):
    """Raised when the _actors directory cannot be created (filesystem error)."""


class ActorNotFound(Exception):
    """Raised when delete_actor cannot locate the actor folder."""


class ActorAlreadyDeleted(Exception):
    """Raised when the actor folder is already under _deleted/."""


class ActorDeleteTargetExists(Exception):
    """Raised when the target path under _deleted/_actors/ already exists."""


class ActorDeleteFailed(Exception):
    """Raised on OS-level failure during the rename / mkdir step of delete_actor."""


@dataclass(frozen=True)
class ActorAttrs:
    ethnicity: str
    gender: str
    age_range: str
    look: str
    style: str
    notes: str = ""

    def to_dict(self) -> dict[str, str]:
        return {
            "ethnicity": self.ethnicity,
            "gender": self.gender,
            "age_range": self.age_range,
            "look": self.look,
            "style": self.style,
            "notes": self.notes,
        }


@dataclass(frozen=True)
class ActorInfo:
    id: str
    attrs: ActorAttrs
    image_path: str
    mtime: float

    def to_dict(self) -> dict[str, object]:
        return {
            "id": self.id,
            "image_path": self.image_path,
            "mtime": self.mtime,
            **self.attrs.to_dict(),
        }


@dataclass
class GenerateResult:
    generated: list[dict[str, object]] = field(default_factory=list)
    errors: list[dict[str, str]] = field(default_factory=list)

    def to_payload(self) -> dict[str, object]:
        return {"generated": list(self.generated), "errors": list(self.errors)}


KLING_BASE_URL: str = "https://api.klingai.com/v1"
KLING_ACCESS_KEY_ENV: str = "KLING_ACCESS_KEY"
KLING_SECRET_KEY_ENV: str = "KLING_SECRET_KEY"
KLING_DEFAULT_MODEL: str = "kling-v1"
KLING_JWT_EXP_SECONDS: int = 1800
KLING_POLL_INTERVAL_SECONDS: float = 2.0
KLING_MAX_WAIT_SECONDS: float = 120.0


def _b64url(data: bytes) -> str:
    """URL-safe base64 without padding (JWT segment encoding)."""
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _make_kling_jwt(access_key: str, secret_key: str, exp_seconds: int = KLING_JWT_EXP_SECONDS) -> str:
    """Build an HS256-signed JWT for Kling API auth, using only stdlib.

    Avoids `PyJWT` dependency. The Kling spec requires iss/exp/nbf claims.
    """
    header = {"alg": "HS256", "typ": "JWT"}
    now = int(time.time())
    payload = {"iss": access_key, "exp": now + exp_seconds, "nbf": now - 5}
    header_b64 = _b64url(json.dumps(header, separators=(",", ":")).encode("utf-8"))
    payload_b64 = _b64url(json.dumps(payload, separators=(",", ":")).encode("utf-8"))
    signing_input = f"{header_b64}.{payload_b64}".encode("ascii")
    signature = hmac.new(secret_key.encode("utf-8"), signing_input, hashlib.sha256).digest()
    sig_b64 = _b64url(signature)
    return f"{header_b64}.{payload_b64}.{sig_b64}"


def _kling_aspect_ratio(width: int, height: int) -> str:
    """Map (width, height) to a Kling-accepted aspect ratio enum.

    Kling does not accept arbitrary dims; it accepts a fixed set of ratio
    enums. Approximate by closest-match.
    """
    if height == 0:
        return "1:1"
    ratio = width / height
    candidates = {
        "1:1": 1.0,
        "16:9": 16 / 9,
        "9:16": 9 / 16,
        "4:3": 4 / 3,
        "3:4": 3 / 4,
    }
    return min(candidates, key=lambda k: abs(candidates[k] - ratio))


def _is_safe_download_host(url: str) -> bool:
    """Reject SSRF-prone hostnames (localhost, private ranges) on Kling's CDN URL."""
    try:
        parsed = urlparse(url)
    except ValueError:
        return False
    if parsed.scheme != "https":
        return False
    host = parsed.hostname
    if not host:
        return False
    try:
        addr_infos = socket.getaddrinfo(host, None)
    except OSError:
        return False
    for info in addr_infos:
        sockaddr = info[4]
        ip_str = sockaddr[0]
        try:
            ip = ipaddress.ip_address(ip_str)
        except ValueError:
            continue
        if ip.is_loopback or ip.is_private or ip.is_link_local or ip.is_multicast or ip.is_reserved:
            return False
    return True


class KlingProvider:
    """Async POST→poll→download against api.klingai.com text-to-image.

    Flow:
      1. POST /images/generations  →  {code: 0, data: {task_id: <uuid>}}
      2. Poll GET /images/generations?pageSize=500 every 2s; find our task
         by task_id; wait for task_status="succeed" (or "failed" → raise).
      3. task_result.images[0].url → SSRF-vet → download bytes.
    """

    name: str = "kling"

    def __init__(
        self,
        access_key: str,
        secret_key: str,
        model: str = KLING_DEFAULT_MODEL,
        base_url: str = KLING_BASE_URL,
        poll_interval: float = KLING_POLL_INTERVAL_SECONDS,
        max_wait: float = KLING_MAX_WAIT_SECONDS,
    ) -> None:
        if not access_key or not secret_key:
            raise ValueError("KlingProvider requires both access_key and secret_key")
        self._ak = access_key
        self._sk = secret_key
        self._model = model
        self._base = base_url.rstrip("/")
        self._poll_interval = poll_interval
        self._max_wait = max_wait

    @classmethod
    def from_env(cls) -> "KlingProvider | None":
        ak = os.environ.get(KLING_ACCESS_KEY_ENV, "").strip()
        sk = os.environ.get(KLING_SECRET_KEY_ENV, "").strip()
        if not ak or not sk:
            return None
        return cls(ak, sk)

    def generate(self, prompt: str, seed: int, width: int, height: int) -> bytes:
        token = _make_kling_jwt(self._ak, self._sk)
        with httpx.Client(timeout=DEFAULT_TIMEOUT_SECONDS, follow_redirects=False) as client:
            task_id = self._submit(client, token, prompt, seed, width, height)
            img_url = self._poll(client, token, task_id)
        if not _is_safe_download_host(img_url):
            raise RuntimeError(f"kling: rejected unsafe download URL: {img_url}")
        with httpx.Client(timeout=DEFAULT_TIMEOUT_SECONDS, follow_redirects=True) as client:
            with client.stream("GET", img_url) as resp:
                resp.raise_for_status()
                buf = bytearray()
                for chunk in resp.iter_bytes():
                    buf.extend(chunk)
                    if len(buf) > MAX_RESPONSE_BYTES:
                        raise ValueError(
                            f"kling: response_too_large (>{MAX_RESPONSE_BYTES} bytes)"
                        )
                return bytes(buf)

    def _submit(
        self,
        client: httpx.Client,
        token: str,
        prompt: str,
        seed: int,
        width: int,
        height: int,
    ) -> str:
        body: dict[str, object] = {
            "model_name": self._model,
            "prompt": prompt,
            "aspect_ratio": _kling_aspect_ratio(width, height),
            "n": 1,
        }
        resp = client.post(
            f"{self._base}/images/generations",
            json=body,
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
            },
        )
        resp.raise_for_status()
        payload = resp.json()
        if payload.get("code") != 0:
            raise RuntimeError(
                f"kling submit: code={payload.get('code')} message={payload.get('message')!r}"
            )
        data = payload.get("data") or {}
        task_id = data.get("task_id")
        if not isinstance(task_id, str) or not task_id:
            raise RuntimeError(f"kling submit: missing task_id in {payload!r}")
        return task_id

    def _poll(self, client: httpx.Client, token: str, task_id: str) -> str:
        start = time.time()
        headers = {"Authorization": f"Bearer {token}"}
        while True:
            if time.time() - start > self._max_wait:
                raise TimeoutError(
                    f"kling: task {task_id} not done in {self._max_wait:.0f}s"
                )
            resp = client.get(
                f"{self._base}/images/generations",
                params={"pageSize": 500},
                headers=headers,
            )
            resp.raise_for_status()
            tasks = (resp.json() or {}).get("data") or []
            for task in tasks:
                if task.get("task_id") != task_id:
                    continue
                status = task.get("task_status")
                if status == "succeed":
                    images = (task.get("task_result") or {}).get("images") or []
                    if not images:
                        raise RuntimeError(
                            f"kling: task {task_id} succeeded with no images"
                        )
                    url = images[0].get("url")
                    if not isinstance(url, str) or not url:
                        raise RuntimeError(
                            f"kling: task {task_id} missing image url"
                        )
                    return url
                if status == "failed":
                    msg = task.get("task_status_msg") or task
                    raise RuntimeError(f"kling: task {task_id} failed: {msg!r}")
                break
            time.sleep(self._poll_interval)


class ActorPool:
    def __init__(
        self,
        exposed: ExposedTree,
        resolver: SafeResolver,
        provider: KlingProvider | None = None,
    ) -> None:
        self._exposed = exposed
        self._resolver = resolver
        if provider is not None:
            self._provider = provider
        else:
            from_env = KlingProvider.from_env()
            if from_env is None:
                raise RuntimeError(
                    f"kling env keys missing; set {KLING_ACCESS_KEY_ENV} + "
                    f"{KLING_SECRET_KEY_ENV} (e.g. via backend/.env loaded by env_loader)"
                )
            self._provider = from_env
        # Per follow-up 033: idempotent one-time filename migration. Cheap
        # when nothing to do (single iterdir on `_actors/`); only acts on
        # folders still carrying the legacy `actor_id.jpg` name.
        try:
            self.migrate_filenames()
        except Exception:
            # Migration is best-effort: must never block app startup.
            pass

    @property
    def provider(self) -> KlingProvider:
        return self._provider

    def actors_dir(self) -> Path:
        return self._exposed.root / "ai_videos" / ACTORS_DIR_NAME

    def preview_prompts(
        self,
        attrs: ActorAttrs,
        count: int,
        resolution: str = DEFAULT_RESOLUTION,
    ) -> dict[str, object]:
        """Dry-run prompt preview (follow-up 032).

        Computes the same {seed, prompt} pairs that `generate_batch` would
        send to Kling, but without allocating actor folders, calling Kling,
        or writing files. The caller can show the user the exact prompts
        and then re-fire the actual generate with `seeds=[...]` set to the
        previewed seeds — that path produces byte-equal Kling requests.
        """
        self._validate_attrs(attrs)
        if not MIN_BATCH_COUNT <= count <= MAX_BATCH_COUNT:
            raise InvalidAttribute(
                f"count must be between {MIN_BATCH_COUNT} and {MAX_BATCH_COUNT}, got {count}"
            )
        if resolution not in RESOLUTION_OPTIONS:
            raise InvalidAttribute(
                f"resolution={resolution!r} not in {sorted(RESOLUTION_OPTIONS)}"
            )
        base_seed = int(time.time() * 1000)
        prompts: list[dict[str, object]] = []
        for i in range(count):
            seed = base_seed + i
            variance = _variance_for(seed, attrs.gender)
            prompt = self._build_prompt(attrs, variance=variance)
            prompts.append({"seed": seed, "prompt": prompt})
        return {"prompts": prompts, "resolution": resolution}

    def generate_batch(
        self,
        attrs: ActorAttrs,
        count: int,
        resolution: str = DEFAULT_RESOLUTION,
        seeds: list[int] | None = None,
    ) -> GenerateResult:
        self._validate_attrs(attrs)
        if not MIN_BATCH_COUNT <= count <= MAX_BATCH_COUNT:
            raise InvalidAttribute(
                f"count must be between {MIN_BATCH_COUNT} and {MAX_BATCH_COUNT}, got {count}"
            )
        if resolution not in RESOLUTION_OPTIONS:
            raise InvalidAttribute(
                f"resolution={resolution!r} not in {sorted(RESOLUTION_OPTIONS)}"
            )
        if seeds is not None:
            if not isinstance(seeds, list) or len(seeds) != count:
                raise InvalidAttribute(
                    f"seeds must be a list of length {count}, got {seeds!r}"
                )
            for s in seeds:
                if not isinstance(s, int):
                    raise InvalidAttribute(f"seeds must be all int, got {seeds!r}")
        actors_dir = self.actors_dir()
        try:
            actors_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            raise GenerationDirMissing(str(exc))

        result = GenerateResult()
        base_seed = int(time.time() * 1000)
        target_px = _RESOLUTION_PRESETS[resolution]
        self._reap_incomplete_folders(actors_dir)
        for i in range(count):
            seed = seeds[i] if seeds is not None else base_seed + i
            try:
                actor_id, actor_folder = self._allocate_actor_id(actors_dir)
            except GenerationDirMissing as exc:
                result.errors.append({"requested_id": f"slot_{i}", "message": f"alloc_failed: {exc}"})
                continue
            variance = _variance_for(seed, attrs.gender)
            prompt = self._build_prompt(attrs, variance=variance)
            try:
                image_bytes = self._provider.generate(prompt, seed, IMAGE_WIDTH, IMAGE_HEIGHT)
            except Exception as exc:
                result.errors.append({"requested_id": actor_id, "message": f"http_failed: {exc}"})
                self._cleanup_empty_folder(actor_folder)
                continue
            if not image_bytes:
                result.errors.append({"requested_id": actor_id, "message": "empty_response"})
                self._cleanup_empty_folder(actor_folder)
                continue
            if target_px is not None:
                try:
                    image_bytes = self._resize_jpeg(image_bytes, target_px)
                except Exception as exc:
                    result.errors.append({"requested_id": actor_id, "message": f"resize_failed: {exc}"})
                    self._cleanup_empty_folder(actor_folder)
                    continue
            jpg_path = actor_folder / _attrs_to_filename(attrs)
            md_path = actor_folder / f"{actor_id}.md"
            try:
                jpg_path.write_bytes(image_bytes)
                md_path.write_text(
                    self._build_sidecar(actor_id, attrs, prompt, seed, resolution),
                    encoding="utf-8",
                )
            except OSError as exc:
                result.errors.append({"requested_id": actor_id, "message": f"write_failed: {exc}"})
                self._cleanup_empty_folder(actor_folder)
                continue
            rel_image = self._rel(jpg_path)
            result.generated.append(
                {
                    "id": actor_id,
                    "image_path": rel_image,
                    "attrs": attrs.to_dict(),
                    "seed": seed,
                    "resolution": resolution,
                }
            )
        return result

    @staticmethod
    def _resize_jpeg(jpeg_bytes: bytes, target_px: int) -> bytes:
        """Resize a JPEG to target_px × target_px using Lanczos resampling.

        Per follow-up 029: Kling returns ~1024×1024 natively for 1:1 aspect;
        the user-pickable resolution dropdown ("2k"/"4k") forces an explicit
        upscale via Pillow's high-quality LANCZOS filter so the saved file
        matches the requested pixel count. Upscaling does not add true
        detail — it is interpolation; recorded in the sidecar.
        """
        img = Image.open(BytesIO(jpeg_bytes)).convert("RGB")
        img = img.resize((target_px, target_px), Image.LANCZOS)
        buf = BytesIO()
        img.save(buf, format="JPEG", quality=JPEG_QUALITY)
        return buf.getvalue()

    def list_actors(self) -> list[ActorInfo]:
        actors_dir = self.actors_dir()
        if not actors_dir.is_dir():
            return []
        out: list[ActorInfo] = []
        for child in sorted(actors_dir.iterdir(), key=lambda p: p.name):
            if not child.is_dir() or child.is_symlink():
                continue
            match = _ACTOR_DIR_RE.match(child.name)
            if not match:
                continue
            actor_id = child.name
            md_path = child / f"{actor_id}.md"
            if not md_path.is_file():
                continue
            jpg_path = _find_actor_jpg(child)
            if jpg_path is None:
                continue
            attrs = self._parse_sidecar(md_path)
            if attrs is None:
                continue
            try:
                mtime = jpg_path.stat().st_mtime
            except OSError:
                continue
            out.append(ActorInfo(id=actor_id, attrs=attrs, image_path=self._rel(jpg_path), mtime=mtime))
        return out

    def actor_exists(self, actor_id: str) -> bool:
        if not _ACTOR_ID_RE.match(actor_id):
            return False
        folder = self.actors_dir() / actor_id
        if not folder.is_dir():
            return False
        return _find_actor_jpg(folder) is not None

    def migrate_filenames(self) -> dict[str, int]:
        """One-time rename pass: legacy `actor_NNNN.jpg` → `{ethnicity}__{gender}__{age_range}.jpg`.

        Per follow-up 033: idempotent. For each `_actors/actor_NNNN/` folder
        that still has the legacy name, parse the sidecar to recover attrs
        and rename the jpg. Folders already on the new naming are skipped.
        Per-folder OSError is logged and counted as an error but does not
        abort the sweep — startup must not block on a single bad file.
        Skips `_deleted/_actors/` (soft-deleted actors are left alone).
        """
        result = {"migrated": 0, "skipped": 0, "errors": 0}
        actors_dir = self.actors_dir()
        if not actors_dir.is_dir():
            return result
        for entry in actors_dir.iterdir():
            if not entry.is_dir() or entry.is_symlink():
                continue
            if not _ACTOR_DIR_RE.match(entry.name):
                continue
            # Already migrated?
            already = any(
                child.is_file() and _NEW_FILENAME_RE.match(child.name)
                for child in entry.iterdir()
            )
            if already:
                result["skipped"] += 1
                continue
            legacy = entry / f"{entry.name}.jpg"
            md = entry / f"{entry.name}.md"
            if not legacy.is_file() or not md.is_file():
                result["skipped"] += 1
                continue
            attrs = self._parse_sidecar(md)
            if attrs is None:
                result["errors"] += 1
                continue
            new_path = entry / _attrs_to_filename(attrs)
            if new_path.exists():
                result["skipped"] += 1
                continue
            try:
                legacy.rename(new_path)
                result["migrated"] += 1
            except OSError:
                result["errors"] += 1
        return result

    def delete_actor(self, actor_id: str) -> dict[str, str]:
        """Soft-delete an actor folder to ai_videos/_deleted/_actors/actor_NNNN/.

        Per follow-up 026: mirrors the mp4 delete pattern (follow-up 023) at
        folder granularity. Atomic Path.rename. Casting cleanup is the
        caller's responsibility (the endpoint runs Casting.unassign_actor_everywhere
        before this rename so dangling references never persist).
        """
        if not _ACTOR_ID_RE.match(actor_id):
            raise InvalidAttribute(f"actor_id={actor_id!r} does not match shape")
        src = self.actors_dir() / actor_id
        if not src.is_dir() or src.is_symlink():
            raise ActorNotFound(f"actor folder not found: {actor_id}")
        target = self._resolver.root / "ai_videos" / "_deleted" / ACTORS_DIR_NAME / actor_id
        if target.exists():
            raise ActorDeleteTargetExists(self._rel(target))
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            raise ActorDeleteFailed(f"mkdir failed: {exc}") from exc
        try:
            src.rename(target)
        except OSError as exc:
            raise ActorDeleteFailed(f"rename failed: {exc}") from exc
        return {"from": self._rel(src), "to": self._rel(target)}

    @staticmethod
    def _validate_attrs(attrs: ActorAttrs) -> None:
        if attrs.ethnicity not in ETHNICITY_OPTIONS:
            raise InvalidAttribute(f"ethnicity={attrs.ethnicity!r} not in schema")
        if attrs.gender not in GENDER_OPTIONS:
            raise InvalidAttribute(f"gender={attrs.gender!r} not in schema")
        if attrs.age_range not in AGE_RANGE_OPTIONS:
            raise InvalidAttribute(f"age_range={attrs.age_range!r} not in schema")
        if attrs.look not in LOOK_OPTIONS:
            raise InvalidAttribute(f"look={attrs.look!r} not in schema")
        if attrs.style not in STYLE_OPTIONS:
            raise InvalidAttribute(f"style={attrs.style!r} not in schema")
        if len(attrs.notes) > 500:
            raise InvalidAttribute("notes must be ≤ 500 characters")

    @staticmethod
    def _build_prompt(attrs: ActorAttrs, variance: str = "") -> str:
        """Build the Kling prompt with anti-wax / anti-AI framing (follow-up 031).

        Removes the prior "photorealistic, sharp focus, 8k" trio — those tokens
        are strongly correlated with CG/render aesthetics in image-model
        training data and tend to nudge Kling toward smooth waxwork faces.
        Replaced with candid-photograph + natural-skin-texture cues so every
        image starts from a "real person photographed by a human" baseline.
        Variance still injects per-image difference between look and style.
        """
        ethn = _ETHNICITY_PROMPT_FRAGMENT[attrs.ethnicity]
        age = _AGE_PROMPT_FRAGMENT[attrs.age_range]
        style = _STYLE_PROMPT_FRAGMENT[attrs.style]
        parts = [
            f"candid unposed portrait photograph of {ethn} {attrs.gender}",
            age,
            attrs.look,
        ]
        if variance:
            parts.append(variance)
        parts.extend([
            style,
            "natural ambient lighting",
            "neutral uncluttered background",
            "natural skin texture with visible pores and subtle imperfections",
            "slight natural facial asymmetry",
            "RAW unedited photograph aesthetic",
            "no plastic skin, no waxy smoothness, no symmetrical perfection, no CG render look",
        ])
        return ", ".join(parts)

    def _allocate_actor_id(self, actors_dir: Path) -> tuple[str, Path]:
        """Atomically claim the next free actor_NNNN id via mkdir(exist_ok=False).

        Per follow-up 027: replaces the old pre-computed `next_id + offset`
        pattern, which lost to itself when 9 concurrent count=1 requests
        all saw the same starting id and raced on the same mkdir. Now each
        allocation walks forward through ids using mkdir as the atomic
        primitive — first thread to win mkdir on actor_K owns it, others
        try actor_K+1, K+2, ... up to _MAX_ID_ALLOC_SCAN attempts.
        """
        start = self._next_actor_id_num(actors_dir)
        candidate = start
        attempts = 0
        while attempts < _MAX_ID_ALLOC_SCAN:
            actor_id = f"actor_{candidate:04d}"
            actor_folder = actors_dir / actor_id
            try:
                actor_folder.mkdir(parents=True, exist_ok=False)
                return actor_id, actor_folder
            except FileExistsError:
                candidate += 1
                attempts += 1
                continue
            except OSError as exc:
                raise GenerationDirMissing(str(exc)) from exc
        raise GenerationDirMissing(
            f"exhausted {_MAX_ID_ALLOC_SCAN} id-allocation attempts starting from actor_{start:04d}"
        )

    @staticmethod
    def _reap_incomplete_folders(actors_dir: Path) -> None:
        """Drop actor_NNNN folders left behind by killed batches (no jpg).

        Per follow-up 018 + 027 + 033: "no jpg" check now uses
        `_find_actor_jpg` which matches both the follow-up 033 descriptive
        filename and the legacy `actor_id.jpg`, so a partly-migrated tree
        does not get reaped as "incomplete".
        """
        try:
            entries = list(actors_dir.iterdir())
        except OSError:
            return
        for entry in entries:
            if not entry.is_dir():
                continue
            if not _ACTOR_DIR_RE.match(entry.name):
                continue
            if _find_actor_jpg(entry) is not None:
                continue
            try:
                for child in entry.iterdir():
                    try:
                        child.unlink()
                    except OSError:
                        pass
                entry.rmdir()
            except OSError:
                pass

    @staticmethod
    def _next_actor_id_num(actors_dir: Path) -> int:
        """Return max+1 across every actor_NNNN folder under actors_dir.

        Pure scan with no side effects (per follow-up 027: reaping moved
        to `_reap_incomplete_folders` so the allocator's mkdir is the
        sole atomic primitive). A folder counts as occupied regardless of
        jpg presence — if a folder exists, its id is taken.
        """
        max_num = 0
        try:
            entries = list(actors_dir.iterdir())
        except OSError:
            return 1
        for entry in entries:
            if not entry.is_dir():
                continue
            m = _ACTOR_DIR_RE.match(entry.name)
            if not m:
                continue
            n = int(m.group(1))
            if n > max_num:
                max_num = n
        return max_num + 1

    @staticmethod
    def _build_sidecar(
        actor_id: str,
        attrs: ActorAttrs,
        prompt: str,
        seed: int,
        resolution: str = DEFAULT_RESOLUTION,
    ) -> str:
        notes_display = attrs.notes if attrs.notes else "—"
        return (
            f"# {actor_id}\n"
            f"\n"
            f"AI-generated actor face (Kling text-to-image, follow-up 025 + 029).\n"
            f"\n"
            f"| 字段 | 值 |\n"
            f"|---|---|\n"
            f"| ethnicity | {attrs.ethnicity} |\n"
            f"| gender | {attrs.gender} |\n"
            f"| age_range | {attrs.age_range} |\n"
            f"| look | {attrs.look} |\n"
            f"| style | {attrs.style} |\n"
            f"| notes | {notes_display} |\n"
            f"| seed | {seed} |\n"
            f"| resolution | {resolution} |\n"
            f"\n"
            f"## 生成 prompt\n"
            f"\n"
            f"```\n"
            f"{prompt}\n"
            f"```\n"
        )

    @staticmethod
    def _parse_sidecar(md_path: Path) -> ActorAttrs | None:
        try:
            text = md_path.read_text(encoding="utf-8")
        except OSError:
            return None
        fields: dict[str, str] = {}
        for line in text.splitlines():
            line = line.strip()
            if not line.startswith("|"):
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            if len(cells) != 2:
                continue
            key, value = cells[0], cells[1]
            if key in {"ethnicity", "gender", "age_range", "look", "style", "notes"}:
                fields[key] = value if value != "—" else ""
        try:
            return ActorAttrs(
                ethnicity=fields["ethnicity"],
                gender=fields["gender"],
                age_range=fields["age_range"],
                look=fields["look"],
                style=fields["style"],
                notes=fields.get("notes", ""),
            )
        except KeyError:
            return None

    def _rel(self, p: Path) -> str:
        try:
            return p.resolve().relative_to(self._resolver.root).as_posix()
        except (OSError, ValueError):
            return p.as_posix()

    @staticmethod
    def _cleanup_empty_folder(folder: Path) -> None:
        try:
            if folder.is_dir() and not any(folder.iterdir()):
                folder.rmdir()
        except OSError:
            pass


__all__ = [
    "ACTORS_DIR_NAME",
    "AGE_RANGE_OPTIONS",
    "ActorAlreadyDeleted",
    "ActorAttrs",
    "ActorDeleteFailed",
    "ActorDeleteTargetExists",
    "ActorInfo",
    "ActorNotFound",
    "ActorPool",
    "DEFAULT_RESOLUTION",
    "ETHNICITY_OPTIONS",
    "GENDER_OPTIONS",
    "GenerateResult",
    "GenerationDirMissing",
    "InvalidAttribute",
    "KLING_ACCESS_KEY_ENV",
    "KLING_BASE_URL",
    "KLING_DEFAULT_MODEL",
    "KLING_SECRET_KEY_ENV",
    "KlingProvider",
    "LOOK_OPTIONS",
    "MAX_BATCH_COUNT",
    "MIN_BATCH_COUNT",
    "RESOLUTION_OPTIONS",
    "STYLE_OPTIONS",
]
